# Generated by Django 5.2 on 2025-05-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='PoliticaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.PositiveIntegerField(help_text='Porcentaje de reembolso (0-100)')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Política de Reembolso',
                'verbose_name_plural': 'Políticas de Reembolso',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehiculo',
                'verbose_name_plural': 'Tipos de Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField(help_text='Numero de pasajeros')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.PositiveIntegerField(default=0, help_text='Kilometraje actual del vehículo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('disponible', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
                ('politica_reembolso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.politicareembolso')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.sucursal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['-ano', 'marca', 'modelo'],
            },
        ),
    ]
