# Generated by Django 5.2 on 2025-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', help_text='Estado actual del vehículo', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_cambio_estado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
