# Generated by Django 5.2 on 2025-05-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_contrasenia_perfil_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
