# Generated by Django 5.2 on 2025-06-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(choices=[('Sucursal Central', 'Sucursal Central'), ('Sucursal Norte', 'Sucursal Norte'), ('Sucursal Sur', 'Sucursal Sur')], max_length=50, verbose_name='Sucursal'),
        ),
    ]
