# Generated by Django 5.2 on 2025-06-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_empleado_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
    ]
