# Generated by Django 5.2 on 2025-05-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_apellido_perfil_contrasenia_perfil_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
