# Generated by Django 5.2 on 2025-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni_conductor',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
