# Generated by Django 5.2.1 on 2025-05-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='usuario',
        ),
    ]
