# Generated by Django 5.2 on 2025-05-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_tarjeta_usuario_reserva_dni_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.tarjeta'),
        ),
    ]
