# Generated by Django 5.2 on 2025-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dni_conductor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
