# Generated by Django 5.2.1 on 2025-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_dni_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='dni_titular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
