# Generated by Django 5.2 on 2025-06-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_tarjeta_dni_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
